sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t quocpc/docker-react .

script:
  - docker run -e CI=true quocpc/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-1"
#   app: "docker-frontend"
#   env: "Dockerfrontend-env"
#   bucket_name: "elasticbeanstalk-ap-northeast-1-005755086822"
#   bucket_path: "docker-frontend"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY